### ISSUE TITLE
Close the dropdown when clicking the link inside it.

### ISSUE THREAD

**Issue by slopesweb** [The73756/dropdown-menu#1]
Wanted to close the dropdown when clicking on the link inside the dropdown.

https://codepen.io/johnquimera/pen/VwdJjMM

**Comment by The73756** [comment]
This functionality was added in the last commit. Now dropdown needs to be called with the ```closeAfterSelect``` parameter - which is responsible for closing on clicking on the link inside the menu. Read more in Readme
