### ISSUE TITLE
text input inside the dropdown.

### ISSUE THREAD

**Issue by slopesweb** [The73756/dropdown-menu#2]
I put a text type input inside the dropdown, but when I click inside the input, the dropdown closes. How to prevent this?

https://codepen.io/johnquimera/pen/VwdJjMM

**Comment by The73756** [comment]
Thanks for the issue. I will try to close both issues over the weekend

**Comment by The73756** [comment]
i fixed it -  https://codepen.io/the73756/pen/dyKxRoG

**Comment by slopesweb** [comment]
@The73756 Thanks.
