### ISSUE TITLE
Демо должно демонстрировать, а не просто лежать!

### ISSUE THREAD

**Issue by Wyndace** [The73756/dropdown-menu#3]
Я, как очень ленивый человек, хочу потыкать в уже что-то готовое, а не скачивать себе на комп, запускать браузер, открывать сайт, тыкать во что-то... Видишь сколько действий надо?

А как этого избежать? Ваще просто:
1.) Добавь GIF'ку, как работает эта штука в Readme
2.) Сделай деплой демо папки на Github Pages и оставь ссылку на этот деплой в Readme
3.) Profit

**Comment by The73756** [comment]
Теперь демо вполне себе демонстрирует демонстрацию работы демонстративного выпадающего меню, думаю что ссылки в Readme на  GitHub Pages будет достаточно. Спасибо за ишью)
